#! /bin/sh

mkdir -p build_pcre2/

cd deps/pcre2/

sh ./configure --with-parens-nest-limit=50000 --with-match-limit=500000000 --enable-static --disable-shared --with-pic --prefix=$PWD/../../build_pcre2/
make
make install
